# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sound_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.penguinImage = QtWidgets.QLabel(self.centralwidget)
        self.penguinImage.setAlignment(QtCore.Qt.AlignCenter)
        self.penguinImage.setObjectName("penguinImage")
        self.verticalLayout.addWidget(self.penguinImage)
        self.soundButton = QtWidgets.QPushButton(self.centralwidget)
        self.soundButton.setObjectName("soundButton")
        self.verticalLayout.addWidget(self.soundButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "키보드 소리 재생"))
        self.soundButton.setText(_translate("MainWindow", "소리 ON"))
